### ISSUE TITLE
sync command improvements

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/pool_tool#20]
based on the csv files in #19 I generated an rsync command. I have some suggestions. 
[sync_cmd.log (.sh not allowed)](https://github.com/esm-tools/pool_tool/files/15292857/sync_cmd.log)

1. while all other commands can have different output files names with -o, this one always dumps into `sync_cmd.sh`
2. The actually rsync commands are missing the maschine login for either pushing or pulling with the resulting command: `rsync -av --files-from=flist/68e6a1d6 /work/ab0246/a270092/input/oasis/cy43r3 /p/project/chhb19/streffing1/input/oasis/cy43r3/T`
3. ~~The error from #19 is here as well~~

**Comment by siligam** [comment]
Dear Jan,

1. I will add `-o` option for this command so the user can specify a custom file name.

2. The machine login details can be included in the sync command by specify either `--lefhost` or `--righthost`.  An example invocation of this command is provided in README.md or by executing `ptool prepare-rsync --help`. 

```sh
> ptool prepare-rsync --righthost a270243@levante.dkrz.de ptool_cy43r3_juwels.csv ptool_cy43r3_levate.csv
Created sync_cmd.sh
> grep a270243 sync_cmd.sh | head -n 1
rsync -av --files-from=flist/cd1100fd /p/project/chhb19/streffing1/input/oasis/cy43r3 a270243@levante.dkrz.de:/work/ab0246/a270092/input/oasis/cy43r3
```

**Comment by JanStreffing** [comment]
Ty @siligam. I will try these features out next time I have pools to sync.
