### ISSUE TITLE
Running checksums.py does not work for some directories

### ISSUE THREAD

**Issue by alxthor** [esm-tools/pool_tool#6]
This problem came up when trying to run the script file generated by `ptool runscript` using `sbatch`.

The job starts and runs for a very long time (>20min) not doing anything.

Manually executing the command in the script
```~/.conda/envs/ptool/bin/python checksums.py /work/ab0246/a270092/input --outfile /home/a/a270205/ptool/use/checksum_AWICM3-JS-2.csv --ignore '.git'```
shows the following error (excerpt):
```
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201702231800
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201706170000
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201904071800
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201909081200
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201705051200
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201712291800
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201801191800
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201912161200
ERROR: skipping /work/ab0246/a270092/input/oifs-43r3/nudging/TCO95L91/sh/rlxmlsh201904161800
```

The problem seems to be linked to the specific pool directory queried. It does not occur for running
```~/.conda/envs/ptool/bin/python checksums.py /pool/data/AWICM/FESOM2 --outfile /home/a/a270205/ptool/use/checksum_fesom2_levante.csv --ignore '.git'```
which exists sucessfully after 17 seconds.

**Comment by siligam** [comment]
As all issues pointed out by @alxthor have been addressed and as there are no further comments received, closing down the issue.
